services:
  postgres_local:
    container_name: postgres_local
    image: postgres:17.5
    # shm_size: 1g
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - postgres_local_data:/var/lib/postgresql/data
    env_file:
      - .env.docker

  pgadmin_local:
    container_name: pgadmin_local
    image: dpage/pgadmin4
    restart: unless-stopped
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-techlead@sonnm.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-12345678}
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin_local_data:/var/lib/pgadmin
      - ./pgadmin-backups:/pgadmin-backups
    env_file:
      - .env.docker

  redis_local:
    image: "redis:8.0.3-alpine"
    container_name: redis_local
    restart: unless-stopped
    volumes:
      - redis_local_data:/data
    ports:
      - "6379:6379"

  mysql:
    image: mysql:8.4.5
    container_name: mysql_local
    restart: unless-stopped
    env_file:
      - .env.docker
    ports:
      - "3306:3306"
    volumes:
      - mysql_local_data:/var/lib/mysql

  mongo:
    image: mongo:8.0.11
    container_name: mongo_local
    restart: unless-stopped
    env_file:
      - .env.docker
    ports:
      - "27017:27017"
    volumes:
      - mongo_local_data:/data/db

networks:
  local:

volumes:
  postgres_local_data:
  redis_local_data:
  pgadmin_local_data:
  mysql_local_data:
  mongo_local_data:
