services:
  postgres:
    container_name: postgres
    image: postgres:16.6
    # shm_size: 1g
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - ./.docker/postgres_init.sql:/docker-entrypoint-initdb.d/postgres_init.sql
      - postgres_data:/var/lib/postgresql/data
    networks:
      - local
    env_file:
      - .env.docker

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: unless-stopped
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-techlead@sonnm.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-12345678}
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./pgadmin-backups:/pgadmin-backups
    networks:
      - local
    env_file:
      - .env.docker

  redis:
    image: "redis:7.2.7-alpine"
    container_name: redis
    restart: unless-stopped
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - local

networks:
  local:

volumes:
  postgres_data:
  redis_data:
  pgadmin_data:
